var _ = require('underscore');
var tipModels = [];

var tipsPriyankaHT = {
	"EXERCISE":[
		"Get active as adults should practice about 150 minutes of moderate intensity exercise every week... Being physically active is important to prevent heart disease and stroke. To improve overall cardiovascular health, experts suggest at least 150 minutes per week of moderate exercise or 75 minutes per week of vigorous exercise (or a combination of moderate and vigorous activity). Thirty minutes a day, five times a week is an easy goal to remember. You will also experience benefits even if you divide your time into two or three segments of 10 to 15 minutes per day. Being physically active could include gardening, walking briskly, bicycling, or other aerobic exercises.",
		"Move your all muscles... Muscle-strengthening activities also provide health benefits and are an important part of an adult's overall physical activity plan. Muscle-strengthening activities are recommended at least two days a week and should work all major muscle groups.",
		"Begin now to become aware of your breath…. Taking time to relax and reducing stress is not a luxury but a health promoting and potentially life-extending technique. The breath is the bridge between the body and mind. Our heartbeat responds to our breathing pattern. It gently accelerates when we inhale and slows when we exhale. Yoga’s emphasis on inhaling slowly, gently, without strain and exhaling completely, is relaxing for the heart muscle. Begin now to become aware of your breath and take time to practise slow, gentle, calm, even breathing. It’s the first step to feeling more relaxed. Yoga breathing exercises teach how to breathe more deeply and rhythmically. Physiologically, it will strengthen respiratory muscles and develop a more efficient exchange of gases. Breathing exercises cause more oxygen to be pushed through the walls of the lungs. Mentally, it will help in improving one’s concentration, willpower, and steadiness.",
		"Something is always better than nothing! Everyone has to start somewhere. What if you can’t make it to the time goal? Even if you've been sedentary for years, today is the day you can begin to make healthy changes in your life. If you don't think you'll make it for 30 or 40 minutes, set a reachable goal for today. You can work up toward your overall goal by increasing your time as you get stronger. Don't let all-or-nothing thinking rob you of doing what you can every day.",
		"Physical activity is anything that makes you move your body and burn calories. This includes things like climbing stairs or playing sports. Aerobic exercises benefit your heart, and include walking, jogging, swimming or biking. Strength and stretching exercises are best for overall stamina and flexibility. The simplest, positive change you can make to effectively improve your heart health is to start walking. It's enjoyable, free, easy, social and great exercise. A walking program is flexible and boasts high success rates because people can stick with it. It's easy for walking to become a regular and satisfying part of life.",
		"Take your child for a brisk walk... It’s a great activity for both man and child and same time an excellent way to get some one-on-one time (or one-on-three, depending on the size of your brood.) Spice up your routine by exploring new neighborhoods or turning your walk into a scavenger hunt.",
		"Mix it up. Variety is good for you... A variety of activity helps you stay interested and motivated. When you include strength and flexibility goals (using weights, resistance bands, yoga and stretching exercises), you also help reduce your chances of injury so you can maintain a good level of heart-healthy fitness for many years.",
		"Reward yourself with something that supports your goals. Pay yourself. Set aside a small amount of money for every workout. After one month, invest your payoff in something that motivates you to keep up the good work, like new music to enjoy while you walk or a new workout shirt. Celebrate your milestones. Fitness needs to a regular part of your life, so finding ways to savor your success is important. Log your walk time or distance and write yourself a congratulatory note when you achieve a milestone, or indulge in a massage after every 100 miles - whatever incentive works to keep you moving!",
		"Warm up and cool down. Warming up before exercising and cooling down afterwards helps your heart move gradually from rest to activity and back again. You also decrease your risk of injury or soreness. Warm-up should last at least 10 minutes — longer for older people and those who have been inactive for a long time. Cool-down is especially important. If you stop exercising too quickly, your blood pressure can drop sharply, which can be dangerous and can also cause muscle cramping. Try adding some relaxing yoga poses to your routine; they will also increase your flexibility."
	],
	"FOOD":["Do you know... Only a Pinch of Sodium is More than Enough Due to high blood pressure, the intake of more than 1550 milligrams of common salt per day can be harmful for your body. So, it is advisable to keep a check on your taste buds for diabetic and hypertension patients. You can replace salt with citrus zest, oregano, ginger and cumin seeds etc. Meals prepared in restaurants usually contain a fairly high amount of sodium as well as other spices, so the patients with hypertension problem should opt for home cooked balanced diet instead of dining out often. Salt makes your body retain water. If you eat too much, the extra water stored in your body raises your blood pressure. This can be a particular problem if you have high blood pressure. Also, eating too much salt may mean that blood pressure medicines, such as diuretics, won't work efficiently.",
"Trying for low Sodium intake..try these... Don’t add salt when cooking. This includes things like soy sauce, curry powders and stock cubes. Get extra flavour with herbs and spices, and from seasonings like chilli, ginger, lemon or lime juice. If you really can't do without a salty favour, you could try using a small amount of low-sodium salt substitute. If you have kidney problems or diabetes, check with your doctor or nurse first. Table sauces like ketchup, mustard and pickles can contain a lot of salt. Check the label and choose low-salt options. Bread and breakfast cereals can contain a lot of salt. Check the labels to compare brands. Smoked meats and fish contain a lot of salt. Avoid these if you can. If you are eating out, ask if your meal can be made with less salt. This may not be possible, but it is always worth asking. Look out for low-salt recipes.",
"Always remember to read food labels to choose products that are lower in sodium! Amount of salt per 100g 0.3g or less - Eat plenty of these 0.3g to 1.5g - Eat small amounts occasionally 1.5g or more - Avoid these completely Some labels may not say how much salt the food contains, but may say how much sodium it contains. Sodium is one of the chemicals in salt. 1g of sodium is the same as 2.5g of salt. If the label does not say how much salt or sodium the food contains, look at the ingredients list. The closer to the top of the list salt appears, the more salt it is likely to contain.",
"Lower blood pressure by eating more fruit and vegetables… Eating more fruit and vegetables has been proven to help lower blood pressure. Fruit and vegetables are full of vitamins, minerals and fibre to keep your body in good condition. They also contain potassium, which helps to balance out the negative effects of salt. This has a direct effect on your blood pressure, helping to lower it.",
"Eat mindfully! Keep Garlic in your home as Garlic will help to slow down your pulse rate as well as smoothen your heart's rhythm to keep your blood pressure in control. Chewing 2-3 raw garlic cloves or ingesting juice of 3-4 garlic cloves everyday would be sufficient.",
"Cooking is your hobby? ..Adopt Heart Healthy Cooking methods as baking, broiling, grilling, roasting, stir frying etc.",
"Moderate Alcohol Levels! Limit Alcohol Intake as Alcohol raises blood pressure and can harm liver, brain, and heart. People with diabetes as well as hypertension should not take alcohol at all, but if you are regular at it then make sure to have at least two alcohol free days a week. Too much alcohol can be harmful as it leads to a rise in level of blood pressure. Man should drink less than 20 units of alcohol in a week and women should not go beyond 15. Pregnant women and those who are trying to be should remain alcohol free during the pregnancy period. Going alcohol free for a long duration lowers the level of blood pressure and improves your overall health also. After consuming alcohol people often overeat as drinking stimulates your appetite, but overeating is not advisable specially for diabetic patients. If you drink too much alcohol, this will raise your blood pressure over time. Alcohol also contains a lot of calories which will make you gain weight. This will also increase your blood pressure. If you keep to the recommended limits for alcohol, this will help to keep your blood pressure down. The current recommended limits are 21 units of alcohol a week for men, and 14 units a week for women.",
"Be sure to spend some quality time with the chefs or cooks in your household and plan together for any dietary changes that are needed.",
"Follow DASH diet : Dietary Approaches to Stop Hypertension High in whole grains, fruits, vegetables, and low-fat dairy Adequate Calcium, Potassium, Magnesium Low in red meat, sweets and sugar beverages Low in saturated and trans fat, cholesterol.",
"Get the most from your fruit and vegetables… Don’t buy fruit and vegetable dishes that come with sauces. They often contain a lot of fat, salt and sugar. Dried, frozen and tinned products can be just as good as fresh, but watch out for added salt, sugar or fats. Vary the types of fruit and vegetables you eat. Each has different health benefits and it will keep your meals interesting. By eating a wide range of fruit and vegetables, you will ensure that your body is getting all the nutrients it needs. Don’t add sugar to fruit or salt to vegetables when you cook or serve them. Try to eat fresh fruit and vegetables as soon as possible. They will lose their nutrients over time, so if you want to store your ingredients for a while, it is best to freeze them or buy frozen packets Avoid leaving vegetables open to the air, light or heat if they have been cut. Always cover and chill them, but don't soak them because the vitamins and minerals can dissolve away. Vegetables keep more of their vitamins and minerals if you lightly steam or bake them, instead of boiling or frying them. If you boil vegetables, use as little water as possible to help keep the vitamins and minerals in them. Experiment with other ways of cooking vegetables, such as roasting or grilling them, for new tastes and flavours. Stir-fries are great for getting lots of vegetables into one meal. So are freshly-made soups.",
"Go Green! To help lower blood pressure, adults should Schedule at least 4 to 5 servings every day of fresh vegetables like beet greens, broccoli, carrots, green leafy vegetables, green beans, green peas, kale, lima beans, potatoes, spinach, squash, sweet potatoes and tomatoes. A portion is 80 grams, or roughly the size of your fist. The following amounts represent a portion: A dessert bowl of salad Three heaped tablespoons of vegetables Three heaped tablespoons of pulses (chickpeas, lentils, beans and so on) One medium-sized fruit (apple, orange, pear or banana) Two smaller fruits (plums, apricots, satsumas) One slice of a large fruit (melon, pineapple or mango) Two to three tablespoons of berries or grapes A glass (150ml) of fruit or vegetable juice One tablespoon of dried fruit",
"Eat enough healthy fats Good fats like monounsaturated fatty acids—can lower bad LDL cholesterol, raise cardio-protective HDL cholesterol, and decrease your risk of atherosclerosis. A higher intake of these fats may also contribute to longer life expectancy. Ideally, you should get about 25% of your daily calories (or 44 g based on a 1,600-calorie diet) from healthy fats. Healthy fats include 1/4 cup of pistachios (7 g), 1/4 cup of almonds (11 g), 1 tablespoon of olive oil (10 g) or 1/4 cup of avocado (3.5 g). So eat 4 to 5 servings every week of nuts like almonds, walnuts and raisins.",
"Avoid frying any of the food items for any kind of meal to keep blood pressure under control.",
"Check Citrus! Remember that citrus fruits and juice, such as grapefruit, can interact with certain medications, so check with your doctor or pharmacist to see if they're OK for you.",
"Avoid foods that are high in saturated fat, cholesterol, and trans fats - sodium, sweets, sugary drinks, red meat, butter and salad dressings to control high blood pressure.",
"Avoid processed foods! Those with high blood pressure should avoid taking processed foods like chips, frozen or canned fruits, canned soups and lunch meats.",
"Cut back on caffeine! Caffeine should best avoided by those looking at controlling high blood pressure. Caffeine often increases your sugar level and blood pressure. If you can’t start your day without a steamy cup of coffee, then you can have coffee made with a paper filter, but you should strictly say no to espresso. Basically paper filters end up soaking the oily component of coffee beans, which if taken directly, can increase the level of cholesterol in your body. The patients having diabetes are recommended to take around 2 cups of coffee (approximate 200 mg) per day. The coffee addicts should consider switching to decaf as it might reduce the level of blood sugar.",
"Using salt free seasionings is a great practical idea to manage high blood pressure.",
"Count you calories and watch your portions, better to write what you eat everytime if you would like to keep a tab on healthy dietary habits.",
"Kwoledge is must! Knowing what to eat and knowing what not to eat is critical good information for those with hypertension, as incorrect eating habits can aggravate the situation.",
"Fancy some fish ? Choose from salmon, herring and tuna as they are all great options for controlling high blood pressure.",
"Go Bonkers for Bananas! Have Bananas with Low Fat Cheese as Bananas are rich in potassium which reduces the harmful effects of sodium naturally and hence helps in keeping blood pressure under control. Bananas contain carbohydrates as well as natural sugar, so you can combine bananas with low fat cheese or peanut butter to reduce the fruit and sugar portion. You can even slice a banana into your breakfast cereal or oatmeal, or take one to work every day for a quick, easy, and inexpensive snack. However, if you are not a big fan of bananas then you can say yes to raw carrots, potatoes, bran flakes, broccoli, nuts, lentils and whole wheat bread. Instead of bananas, one can eat apples and berries which have lower natural sugar content.",
"Say cheers to carrot juice for a healthy heart! Including carrots in your diet will not only help in improving your eyesight, but also work wonders in keeping your heart healthy and weight loss if you are able to maintain a well-balanced diet. In a study published in the Nutrition Journal in 2011, researchers found that drinking 480 ml of fresh carrot juice daily significantly increased antioxidant status and suppressed lipid per oxidation. Lipid per oxidation is a process that takes places naturally where oxidants attack unsaturated fatty acids",
"Trim the Fat Whenever Possible… As a low-fat diet can help you keep to a healthy weight, and this will help to keep your blood pressure down. Eating foods that are low in fat can also help you keep down the level of cholesterol in your blood. Too much cholesterol can raise your risk of heart disease and stroke, so if you have high blood pressure it is very important to keep your cholesterol levels low. Try these: Cut away visible fat from meat and poultry. Roast food on a rack to let the fat drip off. Make soups a day ahead so you can chill them and then remove the fat that has risen to the top.",
"Always remember to read food labels to choose products that are lower in Fats… By reading the food label, you can see if a food is low, medium or high in fat or saturated fat: Low - Less than 3g total fat or 1g saturated fat per 100g of food - These foods are a good choice Medium - Between 3-20g total fat or 1-5g saturated fat per 100g of food - Eat small amounts occasionally High - More than 20g total fat or 5g saturated fat per 100g of food - Avoid these completely",
"The type of fat that you eat is also important… as some types of fats are more likely to raise your cholesterol levels. While other types of fat will help to lower it. Avoid eating too much saturated fat, as this will raise your cholesterol. It is usually found in red meats, butter, palm oil or ghee. In contrast, polyunsaturated fats and monounsaturated fats will help to lower your cholesterol level. They can be found in olive oil, rapeseed oil or sunflower oil. However they will still make you to gain weight if you eat too much of them.",
"Have omega-3s daily Getting the recommended amount can help lower cholesterol, keep cells functioning properly, and combat inflammation, which reduces your risk of cancer, stroke, and heart attack. Flaxseed, walnuts, and some leafy greens contain omega-3s, but seafood is the best source. Take a daily serving of ground flaxseed, walnuts, soybean oil, spinach, or kale. However two serving of seafoods like salmon, herring, lake trout, or other fatty fish would be enough to full fill the requirement. Research published in the Journal of Nutrition found that DHA, an omega-3 found in cold-water, fatty fish, helps maintains healthy circulation in body.",
"Try these tips for drinking less alcohol… Try low-alcohol options – there are now a number of lower-strength beers on the market Check the label – many drinks' labels now tell you how many units they contain Make your drinks last longer by adding mixers or water Don’t eat bar snacks like crisps and peanuts – the added salt will make you want to drink more, and will raise your blood pressure If you drink at home, buy a measure so that you know how much you are drinking.",
"Healthy food shopping lowers blood pressure… If you want to eat the right foods to lower your blood pressure, you need to buy the right foods and avoid the wrong ones. A famous quote says that “Failing to plan is planning to fail”, so always go to the shops armed with a list of what you need. Make sure that you don’t go shopping on an empty stomach. Sticking to the list and not feeling hungry will help you to avoid those impulse purchases. Map your route to avoid the impulse purchases is to follow a “temptation-free” route. Most stores put their processed foods in the centre of the shop, with the staples such as fruit, vegetables, meat, fish and dairy items round the outside. Read the food label and any “traffic lights” on the packet to avoid high-salt, high-fat, high-sugar foods",
"How food \"traffic lights\" work The general advice is : to eat as much \"Green\" as possible, \"Amber\" less often and \"Red\" only as an occasional treat.",
"Stock your kitchen to lower your blood pressure… The best way to give yourself a headstart is to make sure that your kitchen is stocked with the right ingredients like: Wholegrain pasta, breakfast cereals and rice: eating more wholegrains that will help to reduce your risk of heart disease. Brown rice, wholewheat pasta and wholegrain cereals are good choices. Nuts and seeds: these are a good source of minerals and fibre, but they can also be high in fat. A good rule of thumb is no more than handful or two a day. Avoid the roasted and salted types. (Any added salt will act to raise your blood pressure.) Canned fish, fruit, vegetables and beans: canned products can be just as as good as fresh or frozen, but make sure to choose those that have been packed in fresh water or their own juice. Avoid foods that are packed in oil, brine or syrup, or have added salt or sugar. (Again both foods packed in brine or that have been salted will act to raise your blood pressure.)",
"Be choosy about Dairy products: Dairy products can be a good source of calcium (which keeps bones strong), but they can also be high in saturated fat, and some cheeses can be very high in salt. The best choices are skimmed and semi-skimmed milk, low-fat yoghurt, goats’ milk and goats’ cheese or low-fat cheeses such as soft or cottage cheeses.",
"Go for Garlic! Garlic lowers cholesterol and triglyceride that have impact on heart disease. Garlic also help in slowing down the pulse rate. A paste made of about 1 gm of garlic should be mixed with a glass of buttermilk. Drink this buttermilk twice a day. It can bring your blood pressure down. Chewing 2-3 garlic cloves everyday is also an effective way to bring down B.P.",
"Adore Ajwain! Celery (Ajwain) lowers pressure by reducing blood concentration of stress hormones that caused blood vessels to constrict. It is a good natural treatment. Also it fastens the bowel movement and thus helps in weight loss. Regular taking of ajwain also helps to regulate both hypertension and obesity.",
"Go long with Amla! Take juice of4-5 goosberries, mix well with honey and gofor this easy and effective remedy every morning.",
"Use Watermelon as a safeguard! Watermelon is a good safeguard against BP and helps in dilating the blood pressure.",
"How about Healing with Herbs! For centuries Arjuna(Termenalia arjuna)has been used to treat hypertension. Action of mechanism for this particular herb is that it acts like a beta-blocker and is a powerful antioxidant, liver protectant and contains cardio-protective, hypolipidemic, anti-angina and anti-atheroma properties. Gokshura (Tribulus terrestris) is another natural herb used for treating many diseases including hypertension. It has shown to be diuretic and an ACE inhibitor. More herbs like Sarpagandha (Rauwolfia serpentina), Brahmi (Bacopa monnieri), Ashwagandha(Withania somnifera)Shankapushpi (Convolvulus pluricaulis), Chandana ( Santalum album), etc. are also effective herbs which may manage your B.P very well.",
"Stay Strong with Super Spices!",
"Beat your B.P with Beets! Researchers at the Queen Mary University of London found that patients with high blood pressure saw significant improvements in blood pressure from drinking beetroot juice. The study authors concluded that it was the nitrates in the juice that brought down the participants’ blood pressure within just 24 hours. You can juice your own beets or simply cook and eat the whole root. Beetroot is delicious when roasted or when added to stir-fries and stews.",
"Stay Boosted with Potassium! Potassium can lessen the effects of sodium on blood pressure. The best source of potassium is food, such as fruits and vegetables, rather than supplements. Talk to your doctor about the potassium level that's best for you. Leafy greens like romaine lettuce, arugula, kale, turnip greens, collard greens, and spinach are high in potassium.",
"Potatoes are high in both potassium and magnesium, two minerals that can help to lower your blood pressure. They are also high in fiber, which is necessary for an overall healthy diet. Enjoy a baked potato as the centerpiece of your dinner. Instead of fattening and salty butter and sour cream, try adding plain yogurt or salsa for flavor.",
"Feel High with oatmeals! High-fiber, low-fat, and low-sodium foods are just what you want for lowering your blood pressure, and oatmeal fits the bill. Oatmeal for your breakfast is a great way to charge up for the day. On its own, oatmeal can be bland, but refrain from adding too much sugar. Instead, add fresh or frozen berries to sweeten it up, and maybe just a touch of honey.",
"Double your fiber According to research, every additional 10g of dietary fiber consumed daily reduces the risk of death from coronary heart disease by 17%. The daily recommendation of fiber is 25 to 35 g per day. Also fiber may help to protect against cancer and can keep blood sugar levels steady and promote heart health.",
"Pack with protein Eating more protein may help lower systolic blood pressure by more than 2 mmHg in comparison with intake of carbohydrates. Protein provides essential building blocks for the daily repair of nearly every single cell in your body. Getting enough is critical to your health and vitality, especially as you get older, when cellular damage can become more frequent. Aim to get 30% of your daily calories (or 120 g based on a 1,600-calorie diet) from lean protein. Good sources of protein include fat-free milk (8 g per cup), egg whites (7 g for two), skinless white meat from chicken, pork, or turkey (about 21 g per 3 ounces) and beans (about 8 g per 1/2 cup).",
"Follow these tips while eating out: Order foods that are broiled or poached rather than fried or breaded. Cut back on the amount of butter or margarine that you use on bread. Order sauces, gravies, and salad dressings on the side, and use only a little. When you order pasta, choose tomato sauce rather than cream sauce. Ask for salsa with your baked potato instead of sour cream, butter, cheese, or bacon. Don't upgrade your meal to a larger size. Watch portion sizes. Share an entree, or take part of your food home to eat as another meal. Share appetizers and desserts.",
"Consume Fenugreek seeds everyday! Soak 1tsp fenugreek seed in water for a night and munch them early in the morning on empty stomach. It will reduce your cholesterol and excess fats.",
"Try Psyllium husk(Isabgol) for lowering down cholestrol! Psyllium husk(Isabgol) is likely effective for lowering cholesterol in people with high cholesterol. Taking blond psyllium by mouth reduces cholesterol levels in people with mild to moderate high cholesterol. Blond psyllium seed husk or seed added to food or as a separate supplement in a dose of approximately 10-12 grams daily, in combination with a low-fat or a high-fat diet, can reduce levels of total cholesterol by 3% to 14% and low density lipoprotein (LDL or “bad”) cholesterol by 5% to 10 after 7 weeks or more of treatment. Psyllium seems to be less effective in older people. There is some evidence that it lowers LDL cholesterol levels to a lesser degree in people 60 years or older compared to people under 60. Blond psyllium seems to be most effective when taken with foods at mealtime. Breakfast cereal containing blond psyllium can decrease total cholesterol and LDL cholesterol by 5% and 9%, respectively. Blond psyllium also seems to reduce medicine's side effects such as constipation and abdominal pain. However, do not adjust the dose of your medication without consulting your healthcare provider."],
"STRESS":["Don't let stress build up….. The chemicals your body makes in response to stress make your heart beat harder and faster and your blood vessels tighten. All this makes blood pressure higher. Change your expectations. Give yourself time to get things done. Learn to say no and to live within manageable limits. Try to learn to accept things you can't change.",
"Get regular exercise to prevent stress… Try to get at least 30 minutes of activity each day, at least five days a week. Exercise relieves stress and helps you control your weight but try to intentionally enjoy what you do rather than hurrying through your \"relaxing activities\" at a stressful pace.",
"Have a break & go for Yoga Nidra (Savasana)... Yoga Nidra/Savasana or deep relaxation technique teaches how to relax at will, allowing body to release muscle tension almost as it occurs. This is the best of all the techniques, which allows the body to instantly relax at will and prevents from ill effects of stress.",
"Let's get some time for Meditation... Meditation teaches you how to access inner source of strength and personal power, creating a support system that builds confidence and self-esteem, fosters present-moment awareness, increases self-knowledge, and self-awareness.",
"Let's do some yogic exercises.... Chronic stress induced sustained muscular contraction reduces lumen /diameter of blood vessels in the muscles. It in turn increases blood pressure (just as compressing a water pipe increases force of water flow). Stretching of muscles and relaxing the same as done in yogic exercise reverts this effect. Yogic exercises give a good massage to the hardworking heart. Asanas involve minimal muscular activity. In such a condition, the heart has a tendency to slow down and beat in a controlled manner. When the muscular activity is less, there is minimum production of carbon dioxide. This reduces the levels of stress to the heart. One can start with simple stretching postures like Tadasana, Vrikshasana, Ardha chakrasana, Ardha kati chakrasana etc.",
"Feeling Stressed! Just go for meditation in Corpse Pose. Research has now shown that regular practice of Corpse Pose controls high blood pressure. Meditating and practicing breathing exercises regularly are essential to establishing a new relaxation response in place of the hypertensive reflex to stress.",
"Know your stress triggers! Take some time to think about what causes you to feel stressed, such as work, family, finances or illness. Once you know what's causing your stress, consider how you can eliminate or reduce stress. Avoid whatever triggers you can. For example, spend less time with people who bother you or avoid driving in rush-hour traffic.",
"Plan ahead! Think about problems under your control and make a plan to solve them. If you can't eliminate all of your stressors, you can at least cope with them in a healthier way. For example,You could talk to your boss about difficulties at work or to family members about problems at home.",
"Get support ! Supportive family and friends can help improve your health. They may encourage you to take care of yourself, drive you to the doctor's office or promote for an exercise program with you to keep your blood pressure low. If you find you need support beyond your family and friends, consider joining a support group. This may put you in touch with people who can give you an emotional or morale boost and who can offer practical tips to cope with your condition."],
"DO THIS NOT THAT":["Swap out your higher-fat milk for skim milk! The DASH diet recommends increasing the amount of calcium-rich foods that you eat. Skim milk is an excellent source of calcium and is low in fat, another important element of a diet for lowering blood pressure.",
"Instead of sweetened cold cereals, buy oatmeal or other hot cereal.",
"Instead of packaged snacks, buy crackers and peanut butter to make your own little sandwich snacks. Or snack on fresh or dried fruits.",
"Instead of ready-made desserts, make your own cookies, cakes, or muffins.",
"Instead of potato chips, buy unpopped popcorn you can make at home."
],
"GO NATURAL":["Opt for a Healthy Natural Diet! Adding foods that are rich in this mineral to your diet is better than taking supplements, and it’s easy. Moreover diet rich with vitamins fiber and other essential nutrients will give you the power to fight with various diseases and keeping your cholesterol level low."],
"MYTHS BUSTED":["Myth: High blood pressure(High B.P) isn't really a big deal. Fact: Early on, you may not notice symptoms of high blood pressure, so you may not be too concerned. However, in the long run high blood pressure can kill you. According to the Centers for Disease Control (CDC), high blood pressure and high cholesterol are two of the leading risk factors for heart disease and stroke. High blood pressure also can lead to other conditions, such as congestive heart failure, irregular heart rhythm, kidney damage, dementia, and blindness.",
"Myth: In a blood pressure reading, the bottom number is more important than the top. Fact: Blood pressure is typically recorded as two numbers–the systolic pressure (as the heart beats) over the diastolic pressure (as the heart relaxes between beats). For many years, the focus of high blood pressure screening and treatment has been on diastolic blood pressure. However, clinical evidence suggests that controlling both the systolic and diastolic pressure is important to prevent heart attacks and strokes. Blood pressure does change throughout the day, depending on your activities. Blood pressure changes over time, as well. Systolic blood pressure tends to rise as you get older. If either of your blood pressure readings is consistently above normal, then you need to take action right away. You and your doctor can develop a plan to treat high blood pressure or even prehypertension before damage to your organs occurs.",
"Myth: Systolic pressure of 100 + your age is normal. Fact: At any age, having a blood pressure of 140/90 mm Hg or higher is associated with a significantly elevated risk of developing hypertension-related cardiovascular disease, and medical attention is warranted. Optimal blood pressure for an adult is defined as below 120 mm Hg systolic and below 80 mm Hg diastolic; Normal blood pressure for most adults is defined as below 130 mm Hg systolic and below 85 mm Hg diastolic. Normal target blood pressure goals may be even lower for people with certain medical conditions, such as diabetes.",
"Myth: I don’t need to take my blood pressure medication, I feel just fine. Fact: Hypertension can have non-specific symptoms that may go unnoticed for years. However, organ damage and other serious conditions develop over time. It is important to meet the target goal of below 140/90 mm Hg to help avoid long-term complications of hypertension and reduce the risks of heart attack and stroke. For people with certain conditions, like diabetes, target blood pressure goals are even lower (below 130/85 mm Hg.)​​​​",
"Myth: Hypertension cannot be controlled. Fact: Hypertension is easily detected and usually controllable. Making certain lifestyle modifications and taking medication as prescribed are the keys to controlling hypertension. Behavioral changes include losing excess weight, quitting smoking, getting regular exercise, and eating a low-fat and low-salt diet. However, even with such behavioral changes, high blood pressure can still persist. Medication in conjunction with moderate lifestyle alterations is usually necessary to achieve the desired goal of below 140/90 mm Hg.",
"Myth: I don’t use table salt, so I’m in control of my sodium intake and my blood pressure isn’t affected. Fact: In some people, sodium can increase blood pressure. But controlling sodium means more than just putting down the salt shaker. It also means checking labels, because up to 75 percent of the sodium we consume is hidden in processed foods like tomato sauce, soups, condiments, canned foods and prepared mixes. When buying prepared and prepackaged foods, read the labels. Watch for the words \"soda\" and \"sodium\" and the symbol \"Na\" on labels; these words show that sodium compounds are present.",
"Myth: I use kosher or sea salt when I cook instead of regular table salt. They are low-sodium alternatives. Fact: Chemically kosher salt and sea salt are the same as table salt – 40 percent sodium – and count the same toward total sodium consumption. Table salt is a combination of the two minerals sodium (Na) and chloride (Cl).",
"Myth: Take Fresh Vegetables and Fruits for Potassium. Fact: Just avoid canned vegetables as they often have added sodium. Frozen vegetables, on the other hand, contain just as many nutrients as they do when fresh and are easy to store.",
"High blood pressure runs in my family. There is nothing I can do. I will get it too. True/False Right answer is False as high blood pressure can run in families. If your parents or close blood relatives have had high blood pressure, you are more likely to develop it, too. However, lifestyle choices have allowed many people with a family history of high blood pressure to avoid it themselves. You can make healthy lifestyle changes to prevent it.",
"I don’t use table salt, so I’m in control of my sodium intake and my blood pressure isn’t affected. True/False Right answer is False as in some people, sodium can increase blood pressure. But controlling sodium means more than just putting down the salt shaker. It also means checking labels, because up to 75 percent of the sodium we consume is hidden in processed foods like tomato sauce, soups, condiments, canned foods and prepared mixes. When buying prepared and pre-packaged foods, read the labels. Watch for the words \"soda\" and \"sodium\" and the symbol \"Na\" on labels; these words show that sodium compounds are present.",
"If the person is feeling fine, there is no need to worry about high blood pressure. True/False Right answer is False as there are millions of adults who have high blood pressureworldwide – and many of them don’t know it or don’t experience typical symptoms. High blood pressure is serious. If uncontrolled, high blood pressure can lead to severe health problems. High blood pressure is also the No. 1 cause of stroke."],
"DIAGNOSTIC":["Monitor your blood pressure at home and see your doctor regularly! Home monitoring can help you keep tabs on your blood pressure, make certain your lifestyle changes are working, and alert you and your doctor to potential health complications. Blood pressure monitors are available widely and without a prescription. Talk to your doctor about home monitoring before you get started. Regular visits with your doctor are also key to controlling your blood pressure. If your blood pressure is under control, you might need to visit your doctor only every six to 12 months, depending on other conditions you might have. If your blood pressure isn't well-controlled, your doctor will likely want to see you more frequently."],
"LIFESTYLE":["Quit smoking Each cigarette you smoke increases your blood pressure for many minutes after you finish. Quitting smoking helps your blood pressure return to normal. People who quit smoking, regardless of age, have substantial increases in life expectancy.",
"Lose extra pounds and watch your waistline Blood pressure often increases as weight increases. Being overweight also can cause disrupted breathing while you sleep (sleep apnea), which further raises your blood pressure. Weight loss is one of the most effective lifestyle changes for controlling blood pressure. Losing just 10 pounds (4.5 kilograms) can help reduce your blood pressure. Besides shedding pounds, you generally should also keep an eye on your waistline. Carrying too much weight around your waist can put you at greater risk of high blood pressure.",
"Keep a food diary and Watch your eating habbits! Writing down what you eat, even for just a week, can shed surprising light on your true eating habits. Eating a diet that is rich in whole grains, fruits, vegetables and low-fat dairy products and skimps on saturated fat and cholesterol can lower your blood pressure by up to 14 mm Hg. This eating plan is known as the Dietary Approaches to Stop Hypertension (DASH) diet. It isn't easy to change your eating habits, but with maintaining a diary, you can monitor what you eat, how much, when and why."]
};

for (var key in tipsPriyankaHT){
	var subTips = tipsPriyankaHT[key];
	subTips.forEach(function(tip) {
	    var t = {};
	    t.tip = tip;
	    t.category = key;
	    t.createdBy = "priyanka.gupta@callhealth.co.in";
	    t.suitableForDisease = "Hypertension";
	    tipModels.push(t);
	});
}

console.log(tipModels.length);
// console.log(tipModels);

module.exports = function() {
    return tipModels;
};	
